use_frameworks!

platform :ios, '9.0'

target 'BinaryFrameworkExample_Example' do
  pod 'BinaryFrameworkExample', :path => '../'

  target 'BinaryFrameworkExample_Tests' do
    inherit! :search_paths

    
  end
end
