use_frameworks!

platform :ios, '11.0'

target 'BinaryFrameworkExample_Example' do
  pod 'BinaryFrameworkExample', :git => 'git@github.com:chittaponCTO/BinaryFrameworkExample.git'

  target 'BinaryFrameworkExample_Tests' do
    inherit! :search_paths

    
  end
end
